### ISSUE TITLE
bug: Price difference is not displayed for DOTA2 items

### ISSUE THREAD

**Issue by VeZeroDev** [GODrums/BetterBuff#10]
`Price diff` feature works for CS2 items only. I would be nice to show the price diff for DOTA2 items too :)

**Comment by GODrums** [comment]
Thank you for noticing this! 

Even though it is never explicitly stated, this extension is meant to be for CS2 items. 
If you are interested in adapting the code for Dota though, I would be happy to merge it. 

Otherwise I'll just leave this as an open issue for now (won't fix, open for contributions).
